import localFont from "next/font/local";
import "./globals.css";
import { heliosExt, theSignature, Mencken_Std } from "@/lib/fonts";
import Footer from "@/components/Footer";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${heliosExt.variable} ${theSignature.variable} ${Mencken_Std.variable}`}
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-primary`}
      >
        <div className="">{children}</div>
      </body>
      <Footer />
    </html>
  );
}
